blank_issues_enabled: false
contact_links:
  - name: "‚ùì Ask a Question"
    url: "https://github.com/orgs/National-Tutoring-Observatory/discussions"
    about: "Please use our GitHub Discussions for questions, 'how-to' help, and general conversation."
